[workspace]
resolver = "2"
members = [ "binutils", "hcl_macro", "sim", "debugger" ]

[workspace.package]
repository = "https://github.com/sshwy/y86-pipe-rs"

[workspace.dependencies]
tempfile = "3.12.0"
tracing = "0.1"
anyhow = "1.0"