[workspace]
resolver = "2"
members = [ "binutils", "sim_macro", "sim", "debugger" ]

[workspace.package]
repository = "https://github.com/sshwy/y86-pipe-rs"

[workspace.dependencies]
tempfile = "3.15"
tracing = "0.1"
anyhow = "1.0"