[package]
name = "binutils"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tracing-subscriber = { version = "0.3", features = ["json"] }
tempfile.workspace = true
tracing.workspace = true